// Do not edit directly — generated by token-build/build.js
// @codecollab.co/neopop-rn design tokens

import UIKit

public class NeoPopTokens: NSObject {

  // MARK: - Base Colors

  public static let colorBlack = UIColor(red: 13/255, green: 13/255, blue: 13/255, alpha: 1)
  public static let colorWhite = UIColor(red: 255/255, green: 255/255, blue: 255/255, alpha: 1)
  public static let colorRed = UIColor(red: 238/255, green: 77/255, blue: 55/255, alpha: 1)
  public static let colorYellow = UIColor(red: 240/255, green: 141/255, blue: 50/255, alpha: 1)
  public static let colorBlue = UIColor(red: 20/255, green: 76/255, blue: 199/255, alpha: 1)
  public static let colorGreen = UIColor(red: 6/255, green: 194/255, blue: 112/255, alpha: 1)

  // MARK: - Pop Black Scale

  public static let colorPopBlack100 = UIColor(red: 138/255, green: 138/255, blue: 138/255, alpha: 1)
  public static let colorPopBlack200 = UIColor(red: 61/255, green: 61/255, blue: 61/255, alpha: 1)
  public static let colorPopBlack300 = UIColor(red: 22/255, green: 22/255, blue: 22/255, alpha: 1)
  public static let colorPopBlack400 = UIColor(red: 18/255, green: 18/255, blue: 18/255, alpha: 1)
  public static let colorPopBlack500 = UIColor(red: 13/255, green: 13/255, blue: 13/255, alpha: 1)

  // MARK: - Pop White Scale

  public static let colorPopWhite100 = UIColor(red: 210/255, green: 210/255, blue: 210/255, alpha: 1)
  public static let colorPopWhite200 = UIColor(red: 224/255, green: 224/255, blue: 224/255, alpha: 1)
  public static let colorPopWhite300 = UIColor(red: 239/255, green: 239/255, blue: 239/255, alpha: 1)
  public static let colorPopWhite400 = UIColor(red: 251/255, green: 251/255, blue: 251/255, alpha: 1)
  public static let colorPopWhite500 = UIColor(red: 255/255, green: 255/255, blue: 255/255, alpha: 1)

  // MARK: - Poli Purple

  public static let colorPoliPurple0 = UIColor(red: 245/255, green: 240/255, blue: 255/255, alpha: 1)
  public static let colorPoliPurple1 = UIColor(red: 232/255, green: 223/255, blue: 255/255, alpha: 1)
  public static let colorPoliPurple2 = UIColor(red: 212/255, green: 196/255, blue: 255/255, alpha: 1)
  public static let colorPoliPurple3 = UIColor(red: 181/255, green: 158/255, blue: 255/255, alpha: 1)
  public static let colorPoliPurple4 = UIColor(red: 124/255, green: 92/255, blue: 252/255, alpha: 1)
  public static let colorPoliPurple5 = UIColor(red: 91/255, green: 53/255, blue: 213/255, alpha: 1)
  public static let colorPoliPurple6 = UIColor(red: 58/255, green: 31/255, blue: 160/255, alpha: 1)
  public static let colorPoliPurple7 = UIColor(red: 32/255, green: 16/255, blue: 77/255, alpha: 1)

  // MARK: - Orange Sunshine

  public static let colorOrangeSunshine0 = UIColor(red: 255/255, green: 245/255, blue: 239/255, alpha: 1)
  public static let colorOrangeSunshine1 = UIColor(red: 255/255, green: 239/255, blue: 230/255, alpha: 1)
  public static let colorOrangeSunshine2 = UIColor(red: 255/255, green: 217/255, blue: 191/255, alpha: 1)
  public static let colorOrangeSunshine3 = UIColor(red: 255/255, green: 185/255, blue: 133/255, alpha: 1)
  public static let colorOrangeSunshine4 = UIColor(red: 255/255, green: 140/255, blue: 59/255, alpha: 1)
  public static let colorOrangeSunshine5 = UIColor(red: 217/255, green: 96/255, blue: 32/255, alpha: 1)
  public static let colorOrangeSunshine6 = UIColor(red: 160/255, green: 54/255, blue: 16/255, alpha: 1)
  public static let colorOrangeSunshine7 = UIColor(red: 77/255, green: 41/255, blue: 20/255, alpha: 1)

  // MARK: - Park Green

  public static let colorParkGreen0 = UIColor(red: 240/255, green: 255/255, blue: 248/255, alpha: 1)
  public static let colorParkGreen1 = UIColor(red: 221/255, green: 255/255, blue: 241/255, alpha: 1)
  public static let colorParkGreen2 = UIColor(red: 170/255, green: 255/255, blue: 217/255, alpha: 1)
  public static let colorParkGreen3 = UIColor(red: 106/255, green: 255/255, blue: 184/255, alpha: 1)
  public static let colorParkGreen4 = UIColor(red: 46/255, green: 204/255, blue: 132/255, alpha: 1)
  public static let colorParkGreen5 = UIColor(red: 26/255, green: 153/255, blue: 96/255, alpha: 1)
  public static let colorParkGreen6 = UIColor(red: 15/255, green: 102/255, blue: 64/255, alpha: 1)
  public static let colorParkGreen7 = UIColor(red: 18/255, green: 77/255, blue: 52/255, alpha: 1)

  // MARK: - Pink Pong

  public static let colorPinkPong0 = UIColor(red: 255/255, green: 240/255, blue: 243/255, alpha: 1)
  public static let colorPinkPong1 = UIColor(red: 255/255, green: 225/255, blue: 233/255, alpha: 1)
  public static let colorPinkPong2 = UIColor(red: 255/255, green: 194/255, blue: 209/255, alpha: 1)
  public static let colorPinkPong3 = UIColor(red: 255/255, green: 141/255, blue: 170/255, alpha: 1)
  public static let colorPinkPong4 = UIColor(red: 255/255, green: 77/255, blue: 114/255, alpha: 1)
  public static let colorPinkPong5 = UIColor(red: 204/255, green: 34/255, blue: 72/255, alpha: 1)
  public static let colorPinkPong6 = UIColor(red: 153/255, green: 19/255, blue: 44/255, alpha: 1)
  public static let colorPinkPong7 = UIColor(red: 77/255, green: 20/255, blue: 33/255, alpha: 1)

  // MARK: - Mannna

  public static let colorMannna0 = UIColor(red: 255/255, green: 253/255, blue: 240/255, alpha: 1)
  public static let colorMannna1 = UIColor(red: 255/255, green: 248/255, blue: 229/255, alpha: 1)
  public static let colorMannna2 = UIColor(red: 255/255, green: 240/255, blue: 191/255, alpha: 1)
  public static let colorMannna3 = UIColor(red: 255/255, green: 224/255, blue: 128/255, alpha: 1)
  public static let colorMannna4 = UIColor(red: 255/255, green: 204/255, blue: 51/255, alpha: 1)
  public static let colorMannna5 = UIColor(red: 204/255, green: 153/255, blue: 0/255, alpha: 1)
  public static let colorMannna6 = UIColor(red: 153/255, green: 102/255, blue: 0/255, alpha: 1)
  public static let colorMannna7 = UIColor(red: 77/255, green: 61/255, blue: 21/255, alpha: 1)

  // MARK: - Neo Paccha

  public static let colorNeoPaccha0 = UIColor(red: 250/255, green: 255/255, blue: 240/255, alpha: 1)
  public static let colorNeoPaccha1 = UIColor(red: 251/255, green: 255/255, blue: 230/255, alpha: 1)
  public static let colorNeoPaccha2 = UIColor(red: 242/255, green: 255/255, blue: 191/255, alpha: 1)
  public static let colorNeoPaccha3 = UIColor(red: 224/255, green: 255/255, blue: 128/255, alpha: 1)
  public static let colorNeoPaccha4 = UIColor(red: 187/255, green: 255/255, blue: 51/255, alpha: 1)
  public static let colorNeoPaccha5 = UIColor(red: 136/255, green: 204/255, blue: 0/255, alpha: 1)
  public static let colorNeoPaccha6 = UIColor(red: 85/255, green: 122/255, blue: 0/255, alpha: 1)
  public static let colorNeoPaccha7 = UIColor(red: 69/255, green: 76/255, blue: 19/255, alpha: 1)

  // MARK: - Yoyo

  public static let colorYoyo0 = UIColor(red: 250/255, green: 240/255, blue: 255/255, alpha: 1)
  public static let colorYoyo1 = UIColor(red: 244/255, green: 229/255, blue: 255/255, alpha: 1)
  public static let colorYoyo2 = UIColor(red: 232/255, green: 204/255, blue: 255/255, alpha: 1)
  public static let colorYoyo3 = UIColor(red: 209/255, green: 163/255, blue: 255/255, alpha: 1)
  public static let colorYoyo4 = UIColor(red: 169/255, green: 77/255, blue: 255/255, alpha: 1)
  public static let colorYoyo5 = UIColor(red: 123/255, green: 31/255, blue: 212/255, alpha: 1)
  public static let colorYoyo6 = UIColor(red: 82/255, green: 17/255, blue: 158/255, alpha: 1)
  public static let colorYoyo7 = UIColor(red: 51/255, green: 19/255, blue: 77/255, alpha: 1)

  // MARK: - Semantic Error

  public static let colorSemanticError0 = UIColor(red: 252/255, green: 226/255, blue: 221/255, alpha: 1)
  public static let colorSemanticError1 = UIColor(red: 249/255, green: 196/255, blue: 187/255, alpha: 1)
  public static let colorSemanticError2 = UIColor(red: 245/255, green: 157/255, blue: 144/255, alpha: 1)
  public static let colorSemanticError3 = UIColor(red: 241/255, green: 112/255, blue: 96/255, alpha: 1)
  public static let colorSemanticError4 = UIColor(red: 238/255, green: 77/255, blue: 55/255, alpha: 1)

  // MARK: - Semantic Warning

  public static let colorSemanticWarning0 = UIColor(red: 251/255, green: 221/255, blue: 194/255, alpha: 1)
  public static let colorSemanticWarning1 = UIColor(red: 248/255, green: 196/255, blue: 154/255, alpha: 1)
  public static let colorSemanticWarning2 = UIColor(red: 245/255, green: 168/255, blue: 112/255, alpha: 1)
  public static let colorSemanticWarning3 = UIColor(red: 242/255, green: 152/255, blue: 72/255, alpha: 1)
  public static let colorSemanticWarning4 = UIColor(red: 240/255, green: 141/255, blue: 50/255, alpha: 1)

  // MARK: - Semantic Info

  public static let colorSemanticInfo0 = UIColor(red: 194/255, green: 208/255, blue: 242/255, alpha: 1)
  public static let colorSemanticInfo1 = UIColor(red: 155/255, green: 176/255, blue: 232/255, alpha: 1)
  public static let colorSemanticInfo2 = UIColor(red: 110/255, green: 142/255, blue: 220/255, alpha: 1)
  public static let colorSemanticInfo3 = UIColor(red: 64/255, green: 104/255, blue: 207/255, alpha: 1)
  public static let colorSemanticInfo4 = UIColor(red: 20/255, green: 76/255, blue: 199/255, alpha: 1)

  // MARK: - Semantic Success

  public static let colorSemanticSuccess0 = UIColor(red: 230/255, green: 249/255, blue: 241/255, alpha: 1)
  public static let colorSemanticSuccess1 = UIColor(red: 191/255, green: 237/255, blue: 218/255, alpha: 1)
  public static let colorSemanticSuccess2 = UIColor(red: 134/255, green: 221/255, blue: 184/255, alpha: 1)
  public static let colorSemanticSuccess3 = UIColor(red: 62/255, green: 202/255, blue: 138/255, alpha: 1)
  public static let colorSemanticSuccess4 = UIColor(red: 6/255, green: 194/255, blue: 112/255, alpha: 1)

  // MARK: - Spacing

  public static let spacingStep0: CGFloat = 0
  public static let spacingStep1: CGFloat = 4
  public static let spacingStep2: CGFloat = 8
  public static let spacingStep3: CGFloat = 12
  public static let spacingStep4: CGFloat = 16
  public static let spacingStep5: CGFloat = 20
  public static let spacingStep6: CGFloat = 24
  public static let spacingStep7: CGFloat = 28
  public static let spacingStep8: CGFloat = 32
  public static let spacingStep9: CGFloat = 36
  public static let spacingStep10: CGFloat = 40
  public static let spacingStep12: CGFloat = 48
  public static let spacingStep14: CGFloat = 56
  public static let spacingStep16: CGFloat = 64
  public static let spacingXs: CGFloat = 4
  public static let spacingSm: CGFloat = 8
  public static let spacingMd: CGFloat = 16
  public static let spacingLg: CGFloat = 24
  public static let spacingXl: CGFloat = 32
  public static let spacing2xl: CGFloat = 48
  public static let spacingButtonDepth: CGFloat = 3
  public static let spacingButtonDepthTilted: CGFloat = 8
  public static let spacingCardDepth: CGFloat = 3
  public static let spacingBottomSheetNotchHeight: CGFloat = 4
  public static let spacingBottomSheetNotchWidth: CGFloat = 40
  public static let spacingBottomSheetBorderRadius: CGFloat = 16

  // MARK: - Button Sizes

  public static let buttonSizeBigHeight: CGFloat = 50
  public static let buttonSizeBigPaddingHorizontal: CGFloat = 30
  public static let buttonSizeBigIconHeight: CGFloat = 20
  public static let buttonSizeBigFontSize: CGFloat = 16
  public static let buttonSizeBigBorderRadius: CGFloat = 0
  public static let buttonSizeMediumHeight: CGFloat = 40
  public static let buttonSizeMediumPaddingHorizontal: CGFloat = 20
  public static let buttonSizeMediumIconHeight: CGFloat = 16
  public static let buttonSizeMediumFontSize: CGFloat = 14
  public static let buttonSizeMediumBorderRadius: CGFloat = 0
  public static let buttonSizeSmallHeight: CGFloat = 30
  public static let buttonSizeSmallPaddingHorizontal: CGFloat = 25
  public static let buttonSizeSmallIconHeight: CGFloat = 14
  public static let buttonSizeSmallFontSize: CGFloat = 12
  public static let buttonSizeSmallBorderRadius: CGFloat = 0

}
